---
title: "cleaned_entities_v3"
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
library(dplyr)
library(readr)
library(stringr)

entities <- read_csv("entities.csv")
```


# Broader junk pattern
```{r }
junk_patterns <- c(
  "Vol", "St\\.", "pp", "III", "II", "No\\.", "MS", "TT", "esq", "Index",
  "Record", "Certification", "Volume", "fig", "Pan", "4 7", "Zao", "Copy",
  "Resolution", "Memorandum", "Art", "Note", "list", "Table", "Page",
  "Preface", "Introduction", "Appendix", "Contents", "References", "Library",
  "History", "Answer", "Economics"
)
```


# Known academic degrees / initials patterns
```{r }
degree_patterns <- c(
  "A\\.M\\.", "Ph", "M\\.D\\.", "D\\.D\\.S\\.", "B\\.A\\.", "B\\.Sc\\.", "J\\.D\\.", "LL\\.B"
)

subject_stopwords <- c(
  "Library", "Preface", "Index", "Table", "Answer", "Economics", 
  "History", "Introduction", "Appendix", "Notes", "References", "Contents"
)
```


# Systematic corrections
```{r }
entities <- entities %>%
  filter(
    !str_detect(`ENTITY NAME`, regex(paste(junk_patterns, collapse="|"), ignore_case=TRUE)),
    !str_detect(`ENTITY NAME`, regex(paste(degree_patterns, collapse="|"), ignore_case=TRUE)),
    nchar(`ENTITY NAME`) > 2
  ) %>%
  mutate(
    LABEL = case_when(
      str_detect(`ENTITY NAME`, regex("tobacco", ignore_case=TRUE)) ~ "PRODUCT",
      str_detect(`ENTITY NAME`, "\\d+\\s?shilling") ~ "MONEY",
      str_detect(`ENTITY NAME`, regex("Jamestown|James Cittie|Henrico|Elizabeth Cittie|Charles City|Kecoughtan|Powhatan|York|Chesapeake", ignore_case=TRUE)) ~ "GPE",
      LABEL == "PERSON" & str_detect(`ENTITY NAME`, regex(paste(subject_stopwords, collapse="|"), ignore_case=TRUE)) ~ "MISC",
      LABEL == "PERSON" & str_detect(`ENTITY NAME`, regex(paste(degree_patterns, collapse="|"), ignore_case=TRUE)) ~ "MISC",
      TRUE ~ LABEL
    )
  ) %>%
  # improved suspicious logic
  mutate(
    suspicious = case_when(
      str_detect(`ENTITY NAME`, "\\d") & !LABEL %in% c("CARDINAL", "MONEY", "DATE") ~ TRUE,
      LABEL %in% c("GPE","LOC","ORG") & str_detect(`ENTITY NAME`, "\\d") ~ TRUE,
      nchar(`ENTITY NAME`) <= 3 & !LABEL %in% c("CARDINAL", "DATE") ~ TRUE,
      TRUE ~ FALSE
    )
  )
```


```{r }
suspect_entities <- entities %>%
  filter(suspicious)

write_csv(entities, "entities_clean.csv")
write_csv(suspect_entities, "suspect_entities.csv")
```


```{r }

```


```{r }

```